mindmap
  root((Expense Tracker Tech Stack))
     Flutter
      ::icon(fab fa-flutter)
     Firebase
      ::icon(fa fa-fire)
        firebase_auth
         ::icon(fa fa-user-lock)
        cloud_firestore
         ::icon(fa fa-database)
        google_sign_in
         ::icon(fab fa-google)
     Bloc State Management
      ::icon(fa fa-diagram-project)
     go_router Routing
      ::icon(fa fa-route)
     ishar local database
      ::icon(fa fa-hard-drive)

     