blank_issues_enabled: true
contact_links:
  - name: 💬 Discussions
    url: https://github.com/MF-Rozi/Expense-Tracker/discussions
    about: Have a question or idea? Start a discussion!
  - name: 📚 Documentation
    url: https://github.com/MF-Rozi/Expense-Tracker/wiki
    about: Check out our documentation and wiki
